baseURL = "https://rafzmilhomens.github.io/RafaelMMilhomens/"
locale = "pt-br"
title = "Rafael M. Milhomens - BLOG"
languageCode = "pt-br"

[permalinks]
ensaios = "/ensaios/:slug/"
poesia = "/poesia/:slug/"
publicacoes = "/publicacoes/:slug/"
leituras = "/leituras/:slug/"
máquina do sentido = "/máquina do sentido/:slug/"
apoie = "/apoie/:slug/"
sobre = "/sobre/:slug/"


[taxonomies]
tag = "tags"

[params]
author = "Rafael M. Milhomens"
description = "Sobre os mecanismos invisíveis que organizam a percepção coletiva, com foco no Brasil."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.footnote]
        enable = true

disableKinds = ["RSS"]

