baseURL = "https://rafzmilhomens.github.io/RafaelMMilhomens/"
locale = "pt-br"
title = "Rafael M. Milhomens"
languageCode = "pt-br"

[permalinks]
portfolio = "/portfolio/:slug/"

[params]
author = "Rafael M. Milhomens"
description = "Pesquisador independente. Linguagem e sistemas que organizam os sentidos."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.footnote]
        enable = true

disableKinds = ["RSS"]

